### ISSUE TITLE
gps2tsdb asyncio client no longer working.

### ISSUE THREAD

**Issue by facastiblancor** [oats-center/isoblue#165]
When upgrading to python 3.10, asyncio library removed loops from Queue(). This results in the container crashing when initializing the async client.

```
`Traceback (most recent call last):
  File "//./gps2tsdb.py", line 102, in <module>
    loop.run_until_complete(run(loop))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "//./gps2tsdb.py", line 22, in run
    await nc.connect("nats://nats:4222")
  File "/usr/local/lib/python3.10/site-packages/nats/aio/client.py", line 308, in connect
    self._flush_queue = asyncio.Queue(
  File "/usr/local/lib/python3.10/asyncio/queues.py", line 33, in __init__
    super().__init__(loop=loop)
  File "/usr/local/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary
`
```

**Comment by facastiblancor** [comment]
Issue no longer relevant as gpsd2tsdb was replaced by gps_nats
